# Generated by Django 5.0.3 on 2024-03-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='edad',
            new_name='creditos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='email',
        ),
    ]
